import { useState } from "react";
import { Archive, Check, Code2, FileText, FolderKanban, LayoutGrid, List, MoreHorizontal, Plus, Search, StickyNote, Target, X } from "lucide-react";
import { AppShell, SectionLabel } from "./_shared/AppShell";

const initialItems = [{ name: "khmer-weather-app", type: "គម្រោង", meta: "កែប្រែ ២ ម៉ោងមុន", icon: Code2, color: "#66e2dc" }, { name: "កំណត់ត្រា React hooks", type: "កំណត់ត្រា", meta: "ម្សិលមិញ", icon: StickyNote, color: "#f2bd66" }, { name: "ផែនការរៀន Network", type: "ផែនការ", meta: "៣ ថ្ងៃមុន", icon: Target, color: "#9aa9ee" }];
export function IOAI() {
  const [items, setItems] = useState(initialItems);
  const [view, setView] = useState<"grid" | "list">("grid");
  const [showForm, setShowForm] = useState(false);
  const [newName, setNewName] = useState("");
  const addItem = () => { if (newName.trim()) { setItems((current) => [{ name: newName.trim(), type: "គម្រោង", meta: "ទើបបង្កើត", icon: FolderKanban, color: "#71c895" }, ...current]); setNewName(""); setShowForm(false); } };
  return <AppShell active="ioai" title="កន្លែងការងារខ្ញុំ" subtitle="គម្រោង កូដ កំណត់ត្រា និងការរីកចម្រើន — នៅកន្លែងតែមួយ។" eyebrow="IO-AI · MY PERSONAL WORKSPACE">
    <section className="kh-card kh-grid mb-6 p-5 md:p-7"><div className="flex items-start justify-between"><div><p className="kh-eyebrow mb-3">A SMALL SPACE, BIG PLANS</p><h2 className="kh-display max-w-xl text-2xl font-semibold leading-tight text-[#e7f2f1] md:text-3xl">អ្វីដែលអ្នកកំពុង<br /><span className="text-[#71c895]">សាងសង់នៅទីនេះ</span></h2></div><Archive size={22} className="text-[#71c895]" /></div><div className="mt-6 grid grid-cols-3 gap-2"><div className="rounded-xl bg-[#66e2dc]/[.07] p-3"><p className="text-lg font-semibold text-[#66e2dc]">{items.length}</p><p className="text-[10px] text-[#7897a2]">គម្រោង</p></div><div className="rounded-xl bg-[#f2bd66]/[.07] p-3"><p className="text-lg font-semibold text-[#f2bd66]">08</p><p className="text-[10px] text-[#7897a2]">កំណត់ត្រា</p></div><div className="rounded-xl bg-[#9aa9ee]/[.07] p-3"><p className="text-lg font-semibold text-[#9aa9ee]">42%</p><p className="text-[10px] text-[#7897a2]">វឌ្ឍនភាព</p></div></div></section>
    <div className="mb-4 flex items-center justify-between gap-3"><div className="flex flex-1 items-center gap-2 rounded-xl border border-[var(--kh-line)] bg-[#0b202c] px-3 py-2.5"><Search size={15} className="text-[#7897a2]" /><input placeholder="ស្វែងរកក្នុង workspace..." className="w-full bg-transparent text-xs text-[#e7f2f1] outline-none placeholder:text-[#627f8b]" /></div><div className="flex rounded-xl border border-[var(--kh-line)] p-1"><button onClick={() => setView("grid")} className={`rounded-lg p-2 ${view === "grid" ? "bg-[#66e2dc]/10 text-[#66e2dc]" : "text-[#7897a2]"}`}><LayoutGrid size={15} /></button><button onClick={() => setView("list")} className={`rounded-lg p-2 ${view === "list" ? "bg-[#66e2dc]/10 text-[#66e2dc]" : "text-[#7897a2]"}`}><List size={15} /></button></div><button onClick={() => setShowForm((value) => !value)} className="kh-button flex items-center gap-2 rounded-xl bg-[#71c895] px-3 py-2.5 text-[11px] font-semibold text-[#07131d]"><Plus size={14} /><span className="hidden sm:inline">ថ្មី</span></button></div>
    {showForm && <div className="kh-card mb-4 flex gap-2 p-3"><input autoFocus value={newName} onChange={(event) => setNewName(event.target.value)} onKeyDown={(event) => event.key === "Enter" && addItem()} placeholder="ឈ្មោះគម្រោងថ្មី..." className="flex-1 bg-transparent px-2 text-xs text-[#e7f2f1] outline-none placeholder:text-[#627f8b]" /><button onClick={addItem} className="rounded-lg bg-[#71c895] px-3 py-2 text-[10px] font-semibold text-[#07131d]">បង្កើត</button><button onClick={() => setShowForm(false)} className="rounded-lg p-2 text-[#7897a2]"><X size={15} /></button></div>}
    <SectionLabel>ធាតុថ្មីៗ</SectionLabel><div className={view === "grid" ? "grid gap-3 sm:grid-cols-2 lg:grid-cols-3" : "space-y-2"}>{items.map(({ name, type, meta, icon: Icon, color }) => <button key={name} className={`kh-card-soft group flex w-full text-left hover:border-[#71c895]/35 ${view === "grid" ? "min-h-[150px] flex-col justify-between p-4" : "items-center gap-3 p-3"}`}><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl" style={{ color, backgroundColor: `${color}16` }}><Icon size={18} /></span><MoreHorizontal size={15} className="text-[#678590]" /></div><span className={view === "list" ? "flex-1" : ""}><span className="mt-3 block truncate text-xs font-semibold text-[#d9e8e7]">{name}</span><span className="mt-1 flex items-center gap-1 text-[10px] text-[#7897a2]"><FileText size={11} />{type} · {meta}</span></span></button>)}</div>
    <div className="mt-6 flex items-center gap-3 rounded-2xl border border-[#71c895]/15 bg-[#71c895]/[.05] p-4"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#71c895]/10 text-[#71c895]"><Check size={17} /></div><div><p className="text-xs text-[#d9e8e7]">ថ្ងៃនេះអ្នកបានរៀន ២៥ នាទី</p><p className="mt-1 text-[10px] text-[#7897a2]">រក្សាចលនា។ ជំហានតូចៗក៏ជាវឌ្ឍនភាពដែរ។</p></div></div>
  </AppShell>;
}