import { useState } from "react";
import { ArrowRight, BookOpen, Check, ChevronRight, Code2, Cpu, Globe2, Layers3, Network, Shield, Sparkles } from "lucide-react";
import { AppShell, SectionLabel } from "./_shared/AppShell";

const departments = [{ name: "កូដ និង Software", icon: Code2, count: "12 មេរៀន", color: "#66e2dc" }, { name: "Hardware & Circuit", icon: Cpu, count: "8 មេរៀន", color: "#f2bd66" }, { name: "Network Systems", icon: Network, count: "10 មេរៀន", color: "#9aa9ee" }, { name: "សុវត្ថិភាពឌីជីថល", icon: Shield, count: "6 មេរៀន", color: "#71c895" }, { name: "បញ្ញាសិប្បនិម្មិត", icon: Sparkles, count: "9 មេរៀន", color: "#d29feb" }, { name: "ការងារជាក់ស្តែង", icon: Layers3, count: "14 មេរៀន", color: "#e2a783" }];
export function IQAI() {
  const [selected, setSelected] = useState("កូដ និង Software");
  const [started, setStarted] = useState(false);
  return <AppShell active="iqai" title="សាលាបច្ចេកទេស" subtitle="រៀនជាដំណាក់កាល។ សង់ជំនាញដែលអាចប្រើរកចំណូលបាន។" eyebrow="IQ-AI · TECHNICAL ACADEMY">
    <div className="mb-6 flex items-center justify-between rounded-2xl border border-[#f2bd66]/20 bg-[#f2bd66]/[.06] p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f2bd66]/15 text-[#f2bd66]"><Globe2 size={19} /></span><div><p className="text-xs font-semibold text-[#e7f2f1]">ការរៀនមិនគិតថ្លៃ</p><p className="text-[10px] text-[#9aacae]">រៀនតាមល្បឿនរបស់អ្នក · offline-friendly</p></div></div><span className="text-right text-[10px] text-[#f2bd66]">Level 02<br /><span className="text-[#7897a2]">Builder</span></span></div>
    <section className="kh-card kh-grid p-5 md:p-7"><div className="flex items-end justify-between gap-4"><div><p className="kh-eyebrow mb-3">YOUR LEARNING PATH</p><h2 className="kh-display text-2xl font-semibold text-[#e7f2f1] md:text-3xl">ជំនាញដែលអ្នក<br /><span className="text-[#66e2dc]">កំពុងសាងសង់</span></h2></div><div className="hidden text-right md:block"><p className="text-2xl font-semibold text-[#f2bd66]">27%</p><p className="text-[10px] text-[#7897a2]">សរុប</p></div></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-[#183442]"><div className="h-full w-[27%] rounded-full bg-[#f2bd66]" /></div><p className="mt-2 text-[10px] text-[#7897a2]">មេរៀនបន្ទាប់៖ Components និង Props · 18 នាទី</p></section>
    <section className="mt-7"><SectionLabel action="ស្វែងរកវគ្គ">ផ្នែកសិក្សា ៦</SectionLabel><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{departments.map(({ name, icon: Icon, count, color }) => <button key={name} onClick={() => setSelected(name)} className={`kh-button kh-card-soft group flex items-center gap-3 p-4 text-left ${selected === name ? "border-[#66e2dc]/45 bg-[#66e2dc]/[.07]" : "hover:border-white/20"}`}><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl" style={{ color, backgroundColor: `${color}16` }}><Icon size={20} /></span><span className="min-w-0 flex-1"><span className="block text-xs font-semibold text-[#d9e8e7]">{name}</span><span className="mt-1 block text-[10px] text-[#7897a2]">{count}</span></span><ChevronRight size={15} className="text-[#7897a2]" /></button>)}</div></section>
    <section className="kh-card-soft mt-5 flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#66e2dc]/10 text-[#66e2dc]"><BookOpen size={21} /></div><div className="flex-1"><p className="text-[10px] uppercase tracking-[.14em] text-[#66e2dc]">SELECTED PATH</p><h3 className="mt-1 text-sm font-semibold text-[#e7f2f1]">{selected}</h3><p className="mt-1 text-[10px] text-[#7897a2]">វគ្គសិក្សាដែលសមនឹងជំហានបន្ទាប់របស់អ្នក</p></div><button onClick={() => setStarted(true)} className="kh-button flex items-center justify-center gap-2 rounded-xl bg-[#66e2dc] px-4 py-2.5 text-[11px] font-semibold text-[#07131d]">{started ? <><Check size={14} /> កំពុងរៀន</> : <>ចាប់ផ្តើម <ArrowRight size={14} /></>}</button></section>
  </AppShell>;
}