import { useState } from "react";
import { Battery, BookOpen, Car, ChevronRight, CircleHelp, Gauge, Search, Thermometer, Wrench } from "lucide-react";
import { AppShell, SectionLabel } from "./_shared/AppShell";

const topics = [{ title: "ម៉ាស៊ីនមិនចាប់", icon: Car, level: "ចាប់ផ្តើម" }, { title: "ថែទាំថ្មរថយន្ត", icon: Battery, level: "អនុវត្ត" }, { title: "ប្រព័ន្ធត្រជាក់", icon: Thermometer, level: "កម្រិត ២" }];
export function MIK() {
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState("ស្វែងរករោគសញ្ញា");
  return <AppShell active="mik" title="មន្ទីរពិសោធន៍មេកានិច" subtitle="យល់ពីម៉ាស៊ីនដោយដៃខ្លួនឯង — រៀនមុនពេលជួសជុល។" eyebrow="MI-K · MECHANICS & AUTOMOTIVE">
    <div className="kh-card kh-grid mb-5 overflow-hidden p-5 md:p-7"><div className="flex items-start justify-between gap-4"><div><div className="mb-3 flex items-center gap-2 text-[10px] uppercase tracking-[.14em] text-[#e2a783]"><Wrench size={13} /> Repair intelligence</div><h2 className="kh-display max-w-lg text-2xl font-semibold leading-tight text-[#e7f2f1] md:text-3xl">បញ្ហារថយន្ត<br /><span className="text-[#e2a783]">ចាប់ផ្តើមពីការសួរ</span></h2></div><div className="hidden rounded-2xl bg-[#e2a783]/10 p-4 text-[#e2a783] md:block"><Gauge size={28} /></div></div><div className="mt-6 flex rounded-2xl border border-[#e2a783]/20 bg-[#07131d]/60 p-1"><Search size={17} className="m-3 text-[#7897a2]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ឧ. សំឡេងចម្លែកពេលបើកឡាន..." className="w-full bg-transparent text-xs text-[#e7f2f1] outline-none placeholder:text-[#627f8b]" /><button onClick={() => setSelected(query || "ស្វែងរករោគសញ្ញា")} className="rounded-xl bg-[#e2a783] px-4 py-2 text-[11px] font-semibold text-[#07131d]">វិភាគ</button></div></div>
    <div className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><section><SectionLabel action="មើលទាំងអស់">មេរៀនណែនាំសម្រាប់ថ្ងៃនេះ</SectionLabel><div className="space-y-3">{topics.map(({ title, icon: Icon, level }) => <button key={title} onClick={() => setSelected(title)} className="kh-card-soft group flex w-full items-center gap-4 p-4 text-left hover:border-[#e2a783]/35"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#e2a783]/10 text-[#e2a783]"><Icon size={21} /></span><span className="flex-1"><span className="block text-sm font-semibold text-[#d9e8e7]">{title}</span><span className="mt-1 flex items-center gap-2 text-[10px] text-[#7897a2]"><BookOpen size={11} /> 12 នាទី · {level}</span></span><ChevronRight size={16} className="text-[#7897a2] transition-transform group-hover:translate-x-1" /></button>)}</div></section><section className="kh-card p-5"><SectionLabel>តារាងពិនិត្យរហ័ស</SectionLabel><div className="mb-4 flex items-center gap-2 rounded-xl border border-[#f2bd66]/20 bg-[#f2bd66]/[.06] p-3 text-[10px] leading-5 text-[#c8d7d8]"><CircleHelp size={17} className="shrink-0 text-[#f2bd66]" /> ជ្រើសរោគសញ្ញា ដើម្បីចាប់ផ្តើម</div><div className="space-y-2">{["សំឡេង", "កំដៅ", "ភ្លើងព្រមាន", "ការចាប់ផ្តើម"].map((label, index) => <button key={label} onClick={() => setSelected(label)} className={`flex w-full items-center justify-between rounded-xl border p-3 text-[11px] ${selected === label ? "border-[#e2a783]/50 bg-[#e2a783]/10 text-[#e7f2f1]" : "border-[var(--kh-line)] text-[#8caab7]"}`}><span className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${index === 0 ? "bg-[#e2a783]" : index === 1 ? "bg-[#f2bd66]" : "bg-[#9aa9ee]"}`} />{label}</span><ChevronRight size={13} /></button>)}</div><div className="mt-5 border-t border-[var(--kh-line)] pt-4 text-center"><p className="text-[10px] text-[#7897a2]">កំពុងជ្រើសរើស</p><p className="mt-1 text-sm text-[#e2a783]">{selected}</p></div></section></div>
  </AppShell>;
}