// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/AI.tsx": () => import("../components/AI.tsx"),
  "./components/EIT.tsx": () => import("../components/EIT.tsx"),
  "./components/IOAI.tsx": () => import("../components/IOAI.tsx"),
  "./components/IQAI.tsx": () => import("../components/IQAI.tsx"),
  "./components/KI.tsx": () => import("../components/KI.tsx"),
  "./components/MIK.tsx": () => import("../components/MIK.tsx"),
  "./components/Master.tsx": () => import("../components/Master.tsx"),
  "./components/TVAI.tsx": () => import("../components/TVAI.tsx")
};
