// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/khoem-ai/AI.tsx": () => import("../components/mockups/khoem-ai/AI.tsx"),
  "./components/mockups/khoem-ai/EIT.tsx": () => import("../components/mockups/khoem-ai/EIT.tsx"),
  "./components/mockups/khoem-ai/IOAI.tsx": () => import("../components/mockups/khoem-ai/IOAI.tsx"),
  "./components/mockups/khoem-ai/IQAI.tsx": () => import("../components/mockups/khoem-ai/IQAI.tsx"),
  "./components/mockups/khoem-ai/KI.tsx": () => import("../components/mockups/khoem-ai/KI.tsx"),
  "./components/mockups/khoem-ai/MIK.tsx": () => import("../components/mockups/khoem-ai/MIK.tsx"),
  "./components/mockups/khoem-ai/Master.tsx": () => import("../components/mockups/khoem-ai/Master.tsx")
};
