import { ArrowUpRight, BookOpen, Camera, Code2, Database, LockKeyhole, Mic, Network, Plus, ShieldCheck, Wrench, Zap } from "lucide-react";
import { AppShell, goTo, SectionLabel, StatusDot } from "./_shared/AppShell";

const systems = [
  { key: "ai" as const, name: "AI", khmer: "ជំនួយការកូដ", icon: Code2, color: "#66e2dc", detail: "សួរ · បង្កើត · ពន្យល់", signal: "កំពុងដំណើរការ" },
  { key: "ki" as const, name: "KI", khmer: "ភ្នែកឆ្លាត", icon: Camera, color: "#f2bd66", detail: "មើល · ស្គាល់ · រៀន", signal: "พร้อมប្រើ" },
  { key: "mik" as const, name: "MI-K", khmer: "មេកានិច", icon: Wrench, color: "#e2a783", detail: "ជួសជុល · យល់ដឹង", signal: "កំពុងដំណើរការ" },
  { key: "eit" as const, name: "EI-T", khmer: "អេឡិចត្រូនិក", icon: Network, color: "#9aa9ee", detail: "ភ្លើង · បណ្តាញ · Tech", signal: "កំពុងដំណើរការ" },
  { key: "iqai" as const, name: "IQ-AI", khmer: "សាលាបច្ចេកទេស", icon: BookOpen, color: "#c49bee", detail: "រៀនជាដំណាក់កាល", signal: "វគ្គថ្មី ៣" },
  { key: "ioai" as const, name: "IO-AI", khmer: "កន្លែងការងារខ្ញុំ", icon: Database, color: "#71c895", detail: "គម្រោង · កំណត់ត្រា", signal: "ថ្មី" },
];

export function Master() {
  return <AppShell active="master" title="មជ្ឈមណ្ឌលបញ្ជា" subtitle="ថ្ងៃនេះ អ្នកកំពុងសាងសង់អ្វីមួយដែលមានន័យ។" eyebrow="KHOEM-AI MASTER ENGINE">
    <section className="kh-card kh-grid relative overflow-hidden p-5 md:p-7">
      <div className="absolute -right-12 -top-16 h-48 w-48 rounded-full border border-[#66e2dc]/10 bg-[#66e2dc]/5 blur-2xl" />
      <div className="relative flex items-start justify-between gap-4"><div><div className="mb-3 flex items-center gap-2 text-[11px] text-[#66e2dc]"><StatusDot />ប្រព័ន្ធមានសុខភាពល្អ</div><h2 className="max-w-lg kh-display text-2xl font-semibold leading-tight text-[#e7f2f1] md:text-4xl">មួយកន្លែងសម្រាប់<br /><span className="text-[#66e2dc]">រៀន បង្កើត និងជួសជុល</span></h2><p className="mt-3 max-w-md text-xs leading-6 text-[#8caab7]">KHOEM-AI ជាម៉ាស៊ីនគិតផ្ទាល់ខ្លួន សម្រាប់ការរៀនដោយឥតគិតថ្លៃ និងធ្វើការតាមទូរស័ព្ទ។</p></div><div className="kh-float hidden h-20 w-20 place-items-center rounded-3xl border border-[#f2bd66]/25 bg-[#f2bd66]/10 md:grid"><Zap size={30} className="text-[#f2bd66]" /></div></div>
      <div className="relative mt-6 flex flex-wrap gap-2"><span className="rounded-full bg-[#66e2dc]/10 px-3 py-1.5 text-[10px] text-[#66e2dc]">6 systems online</span><span className="rounded-full bg-[#f2bd66]/10 px-3 py-1.5 text-[10px] text-[#f2bd66]">Secure Vault ready</span></div>
    </section>
    <section className="mt-7"><SectionLabel action="មើលទាំងអស់">ប្រព័ន្ធរងរបស់អ្នក</SectionLabel><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{systems.map((system) => { const Icon = system.icon; return <button key={system.key} onClick={() => goTo(system.key)} className="kh-button kh-card-soft group flex items-center gap-3 p-4 text-left hover:-translate-y-0.5 hover:border-[#66e2dc]/30"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl" style={{ color: system.color, backgroundColor: `${system.color}16`, border: `1px solid ${system.color}28` }}><Icon size={20} /></span><span className="min-w-0 flex-1"><span className="flex items-center justify-between"><span className="kh-display text-sm font-semibold text-[#e7f2f1]">{system.name}</span><ArrowUpRight size={14} className="text-[#63818c] transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></span><span className="block text-xs text-[#b6c6c7]">{system.khmer}</span><span className="mt-1 block truncate text-[10px] text-[#7897a2]">{system.detail} · <span style={{ color: system.color }}>{system.signal}</span></span></span></button>; })}</div></section>
    <section className="mt-7 grid gap-3 md:grid-cols-[1.4fr_1fr]"><div className="kh-card p-5"><SectionLabel action="បើកកំណត់ហេតុ">សញ្ញាប្រព័ន្ធ · SYSTEM HEALTH</SectionLabel><div className="space-y-4">{[["Master Engine", "ភ្ជាប់បានល្អ", "100%"], ["Secure Vault", "ការពារទិន្នន័យ", "92%"], ["API Bridge", "ត្រៀមរួច", "84%"]].map(([label, status, value], index) => <div key={label}><div className="mb-1.5 flex justify-between text-xs"><span className="text-[#c8d7d8]">{label} <span className="ml-2 text-[10px] text-[#7897a2]">{status}</span></span><span className={index === 1 ? "text-[#f2bd66]" : "text-[#66e2dc]"}>{value}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[#183442]"><div className={`h-full rounded-full ${index === 1 ? "bg-[#f2bd66]" : "bg-[#66e2dc]"}`} style={{ width: value }} /></div></div>)}</div></div><div className="kh-card-soft p-5"><SectionLabel>សកម្មភាពរហ័ស</SectionLabel><div className="grid grid-cols-2 gap-2"><button onClick={() => goTo("ai")} className="kh-button flex flex-col gap-3 rounded-2xl border border-[#66e2dc]/15 bg-[#66e2dc]/[.06] p-3 text-left"><Code2 size={18} className="text-[#66e2dc]" /><span className="text-[11px] text-[#d5e4e3]">សួរ AI</span></button><button onClick={() => goTo("ki")} className="kh-button flex flex-col gap-3 rounded-2xl border border-[#f2bd66]/15 bg-[#f2bd66]/[.06] p-3 text-left"><Camera size={18} className="text-[#f2bd66]" /><span className="text-[11px] text-[#d5e4e3]">បើកកាមេរ៉ា</span></button><button onClick={() => goTo("ioai")} className="kh-button flex flex-col gap-3 rounded-2xl border border-[#9aa9ee]/15 bg-[#9aa9ee]/[.06] p-3 text-left"><Plus size={18} className="text-[#9aa9ee]" /><span className="text-[11px] text-[#d5e4e3]">គម្រោងថ្មី</span></button><button className="kh-button flex flex-col gap-3 rounded-2xl border border-[#71c895]/15 bg-[#71c895]/[.06] p-3 text-left"><Mic size={18} className="text-[#71c895]" /><span className="text-[11px] text-[#d5e4e3]">សំឡេង</span></button></div></div></section>
    <div className="mt-5 flex items-center justify-center gap-2 text-[10px] text-[#6f8c98]"><LockKeyhole size={12} /> កន្លែងផ្ទាល់ខ្លួន · ទិន្នន័យនៅជាមួយអ្នក</div>
  </AppShell>;
}